# Generated by Django 4.0.4 on 2022-10-24 14:52

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Username', models.CharField(default='', max_length=100)),
                ('First_Name', models.CharField(default='', max_length=150)),
                ('Last_Name', models.CharField(default='', max_length=150)),
                ('Message', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', embed_video.fields.EmbedVideoField()),
                ('Title', models.CharField(default='', max_length=100)),
                ('Description', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
